version: "3.8"
services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    ports:
      - "5000:5000"
    command: sh -c "npx prisma migrate deploy && npm run server"  # Fixed spacing
    environment:
      CHOKIDAR_USEPOLLING: true
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}  # Fixed port
      LOGO_URL: ${LOGO_URL}
      JWT_SECRET: ${JWT_SECRET}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      CORS_ORIGIN: ${CORS_ORIGIN}
      PORT: 5000
    working_dir: /usr/src/app
    depends_on:
      db:
        condition: service_healthy
    tty: true
    networks:
      - it-network
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile  # Needs prod build
    container_name: frontend
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - it-network
    environment:
      - VITE_BACKEND_URL= ${VITE_BACKEND_URL}
      - CHOKIDAR_USEPOLLING=true

  db:
    image: postgres:17-alpine
    container_name: db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - it-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 60s
      retries: 5
    ports:
      - "5432:5432"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx_it-khiva
    environment:
      DOMAIN: ${DOMAIN}
      EMAIL: ${EMAIL}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - backend
      - frontend
    networks:
      - it-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email xikmatkiva.4s@gmail.com -d it-khiva.uz --agree-tos

volumes:
  db_data:
  frontend_build:  # New shared volume

networks:
  it-network:
    driver: bridge  # ✅ CORRECT - default & works fine